### ISSUE TITLE
MongoDB tests failing on python 2.6

### ISSUE THREAD

**Issue by gi0baro** [web2py/pydal#244]
Dunno why they started failing with my commit (changelog and version edited..), but is happening: https://travis-ci.org/web2py/pydal/jobs/69286538

@stephenrauch any ideas?

**Comment by cassiobotaro** [comment]
assertRaises expect as parameter the  Exception and the function to be evaluated.

This behaviour change in python 2.7

https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises

**Comment by stephenrauch** [comment]
I also have no idea why it started failing a week after I submitted it.  I removed the line altogether in https://github.com/web2py/pydal/pull/242 which is currently waiting to be merged.  The test was poorly formed, and I re-implemented the test and added several other mongo specific tests.  

I just pushed a change to https://github.com/web2py/pydal/pull/242 which reverts the changes to base.represent(). Since all of the changes are now in the mongo driver, maybe it could now be merged?
