### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#60]
I'm wondering if python 2.5 is still considered as supported or not by pydal.
The readme should explicitly state the python versions considered as stable and 'supported', the ones marked as 'experimental' (I guess jython?), and those not supported at all (python 3.x ?)

**Comment by gi0baro** [comment]
I think we should drop support for python 2.5, making pyDAL officially supporting 2.6.x and 2.7.x
2.5 is too old, and right now many linux distributions are shipped with 2.7

Regarding python 3.x: I started making some work a couple of months ago, I will update the codebase to create a *py3* branch on the repository. However, we should start a deepen discussion about python 3 due to bytes/unicode strings changes from 2.x

**Comment by niphlod** [comment]
Until web2py drops support for 2.5 pydal can't drop it...

**Comment by mdipierro** [comment]
I would very much a web3py version of the dal. For this purpose I would not oppose a fork. Since we are at it we should consider other changes:

1) (query).select() instead of db(query).select()

2) lazy parsing of the data returned by the db into objects, perhaps return an iterator instead of the actual Rows.

**Comment by niphlod** [comment]
web3py means python3 ? 

BTW: I didn't want to enforce support for 2.5 (I'm one of the "early adopters of ditching it"), but that the drop should be related to the same drop in web2py.

**Comment by ilvalle** [comment]
2015-02-17 19:06 GMT+01:00 mdipierro <notifications@github.com>:

> I would very much a web3py version of the dal. For this purpose I would
> not oppose a fork. Since we are at it we should consider other changes:
>
> 1) (query).select() instead of db(query).select()
>

I like it but how do you envision it?

2) lazy parsing of the data returned by the db into objects, perhaps return
> an iterator instead of the actual Rows.


This is on trello todolist
Lets move this discussion of this changes on the list?

Paolo

**Comment by gi0baro** [comment]
Btw, how can we guarantee support to python 2.5.x on web2py and pyDAL if we're not testing it?

**Comment by niphlod** [comment]
see https://github.com/web2py/web2py/issues/798#issuecomment-74949556
